# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcca3eae016b1cb80685ae60bda0a0a644ea040f6f92cd134236c5a83718e671bc72abffc029027558f362a286ed70106c8cb866b7a0451686faf8e68efc4785

test:
  secret_key_base: 8ad733be01a640aab64150763f69e365a110b48232f8b793140ac9c5644e334f6335d2c4875241044df0af25d5bdb922769fee2c0d4057754710de8f0acc36ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
